version: '2'
services:
    oori:
      image: biotope/oori
      environment:
        - SERVER_PORT=9090
        - ENDPOINT_URL=http://fuseki:3030/odfData
        - CB_HOSTNAME=oori
        - CB_PORT=9090
      ports:
        - "9090:9090"
        - "5005:5005"   # java debugging

    fuseki:
      build: fuseki/
      ports:
        - "3030:3030"

#    o-mi-node:
#      build: o-mi-node/
#      ports:
#       - "8080:8080"